steps:
  # Paso 1: Instalar y Testear (Todo en uno para eficiencia)
  - name: 'python:3.9'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          pip install --upgrade pip
          pip install -r app/requirements.txt
          python -m unittest discover tests

  # Paso 2: Build de la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-east1-docker.pkg.dev/oval-turbine-495504-h2/mydockerresgistry-jhon/myapp:$BUILD_ID'
      - '.'

# El 'push' se maneja automáticamente si la imagen está en esta lista
images:
  - 'us-east1-docker.pkg.dev/oval-turbine-495504-h2/mydockerresgistry-jhon/myapp:$BUILD_ID'

logsBucket: "gs://lab1-static-site-jhon"
